"""Add missing columns

Revision ID: 1e0471e56de4
Revises: 450e2310a5af
Create Date: 2025-12-18 10:46:35.693814

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e0471e56de4'
down_revision = '450e2310a5af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_message')
    op.drop_table('vehicle')
    op.drop_table('ride')
    with op.batch_alter_table('passenger_ride', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_passenger_ride_booking'))

    op.drop_table('passenger_ride')
    with op.batch_alter_table('driver_location', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('driver_id'))

    op.drop_table('driver_location')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('driver_license_id'))
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('phone_number'))

    op.drop_table('user')
    op.drop_table('review')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ride_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reviewer_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reviewee_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['reviewee_id'], ['user.id'], name=op.f('review_ibfk_1')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], name=op.f('review_ibfk_2')),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.id'], name=op.f('review_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('full_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('role', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('is_identity_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('driver_license_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('is_license_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('bio', mysql.TEXT(), nullable=True),
    sa.Column('average_rating', mysql.FLOAT(), nullable=True),
    sa.Column('total_ride_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('phone_number'), ['phone_number'], unique=True)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('driver_license_id'), ['driver_license_id'], unique=True)

    op.create_table('driver_location',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('driver_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('latitude', mysql.FLOAT(), nullable=False),
    sa.Column('longitude', mysql.FLOAT(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['user.id'], name=op.f('driver_location_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('driver_location', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('driver_id'), ['driver_id'], unique=True)

    op.create_table('passenger_ride',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('passenger_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ride_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('seats_booked', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('booked_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['passenger_id'], ['user.id'], name=op.f('passenger_ride_ibfk_1')),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.id'], name=op.f('passenger_ride_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('passenger_ride', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_passenger_ride_booking'), ['passenger_id', 'ride_id'], unique=True)

    op.create_table('ride',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('driver_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vehicle_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('origin', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('destination', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('departure_time', mysql.DATETIME(), nullable=False),
    sa.Column('total_seats', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('available_seats', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['user.id'], name='ride_ibfk_1'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], name='ride_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('vehicle',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('make', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('model', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('color', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('license_plate', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('seat_capacity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='vehicle_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('chat_message',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ride_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sender_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('receiver_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], name=op.f('chat_message_ibfk_3')),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.id'], name=op.f('chat_message_ibfk_1')),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name=op.f('chat_message_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
