"""Final check for missing columns

Revision ID: 43e9e31e6084
Revises: 90533dc6c75d
Create Date: 2025-11-28 06:18:18.754489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43e9e31e6084'
down_revision = '90533dc6c75d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_ride_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('total_ride_count')
        batch_op.drop_column('average_rating')

    # ### end Alembic commands ###
