"""add receiver id to the message model

Revision ID: 53942f256a6c
Revises: ea2f0e01134f
Create Date: 2025-12-18 08:53:14.619514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53942f256a6c'
down_revision = 'ea2f0e01134f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiver_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['receiver_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('receiver_id')

    # ### end Alembic commands ###
