"""Added Vehicle model

Revision ID: 90533dc6c75d
Revises: 571251dacc5a
Create Date: 2025-11-28 06:06:28.806185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90533dc6c75d'
down_revision = '571251dacc5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('make', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('license_plate', sa.String(length=10), nullable=False),
    sa.Column('seat_capacity', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_plate')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle')
    # ### end Alembic commands ###
